- 0
- 4  # Berlin United
- 5  # B-Human
- 8  # Dutch Nao Team
- 12  # Nao Devils
- 13  # HTWK Robots
- 17  # RoboEireann
- 18  # rUNSWift
- 19  # SPQR Team
- 24  # HULKs
- 45  # Naova
- 51  # RedBackBots
- 54  # WisTex United
- 70  # B-Team
